/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg1;

import javax.swing.JOptionPane;

/**

 * Esta clase define la clase Interfaz, donde la cual se puede ver la construccion de la interfaz
  
 * @author: Ricardo Paez - Luciano Minardo - Gabriele Colarusso

 * @version: 15/10/2024

 */

public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        redTransporte = new javax.swing.JLabel();
        nroParadas = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tipoBusqueda = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        redTransporteSeleccionado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCargarRed = new javax.swing.JMenu();
        menuItemCaracas = new javax.swing.JMenuItem();
        menuItemBogota = new javax.swing.JMenuItem();
        menuItemOtro = new javax.swing.JMenuItem();
        menuPreferencias = new javax.swing.JMenu();
        menuItemParada = new javax.swing.JMenuItem();
        menuTipoBusqueda = new javax.swing.JMenu();
        menuItemProfundidad = new javax.swing.JMenuItem();
        menuItemAmplitud = new javax.swing.JMenuItem();
        menuAgregarLinea = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Red Transporte: ");

        redTransporte.setText(" ");

        nroParadas.setText(" ");

        jLabel3.setText("Nro Parada ( t ) = ");

        tipoBusqueda.setText(" ");

        jLabel4.setText("Tipo Busqueda: ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(redTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(redTransporteSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nroParadas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoBusqueda))
                        .addGap(606, 606, 606)
                        .addComponent(redTransporte, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nroParadas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(redTransporteSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 680, 740, 50));

        menuCargarRed.setText("Cargar Red");

        menuItemCaracas.setText("Caracas");
        menuItemCaracas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCaracasActionPerformed(evt);
            }
        });
        menuCargarRed.add(menuItemCaracas);

        menuItemBogota.setText("Bogota");
        menuItemBogota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBogotaActionPerformed(evt);
            }
        });
        menuCargarRed.add(menuItemBogota);

        menuItemOtro.setText("Otro");
        menuItemOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemOtroActionPerformed(evt);
            }
        });
        menuCargarRed.add(menuItemOtro);

        jMenuBar1.add(menuCargarRed);

        menuPreferencias.setText("Preferencias");

        menuItemParada.setText("Nro de Paradas(t)");
        menuItemParada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemParadaActionPerformed(evt);
            }
        });
        menuPreferencias.add(menuItemParada);

        menuTipoBusqueda.setText("Tipo de Busqueda");

        menuItemProfundidad.setText("en Profundidad (DFS)");
        menuItemProfundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemProfundidadActionPerformed(evt);
            }
        });
        menuTipoBusqueda.add(menuItemProfundidad);

        menuItemAmplitud.setText("en Amplitud (BFS)");
        menuItemAmplitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAmplitudActionPerformed(evt);
            }
        });
        menuTipoBusqueda.add(menuItemAmplitud);

        menuPreferencias.add(menuTipoBusqueda);

        jMenuBar1.add(menuPreferencias);

        menuAgregarLinea.setText("Agregar Linea");
        jMenuBar1.add(menuAgregarLinea);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemCaracasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCaracasActionPerformed
       redTransporteSeleccionado.setText("Caracas");
    }//GEN-LAST:event_menuItemCaracasActionPerformed

    private void menuItemProfundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemProfundidadActionPerformed
        tipoBusqueda.setText("en Profundidad (DFS) ");
    }//GEN-LAST:event_menuItemProfundidadActionPerformed

    private void menuItemAmplitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAmplitudActionPerformed
        tipoBusqueda.setText("en Amplitud (BFS)");
    }//GEN-LAST:event_menuItemAmplitudActionPerformed

    private void menuItemParadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemParadaActionPerformed
        String input = "";
        input = JOptionPane.showInputDialog("Ingrese el número de Paradas (t): ");
        int t = Integer.parseInt(input);
        nroParadas.setText(String.valueOf(t));
    }//GEN-LAST:event_menuItemParadaActionPerformed

    private void menuItemBogotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBogotaActionPerformed
        redTransporteSeleccionado.setText("Bogota");
    }//GEN-LAST:event_menuItemBogotaActionPerformed

    private void menuItemOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemOtroActionPerformed
        redTransporteSeleccionado.setText("Otra");
    }//GEN-LAST:event_menuItemOtroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JMenu menuAgregarLinea;
    private javax.swing.JMenu menuCargarRed;
    private javax.swing.JMenuItem menuItemAmplitud;
    private javax.swing.JMenuItem menuItemBogota;
    private javax.swing.JMenuItem menuItemCaracas;
    private javax.swing.JMenuItem menuItemOtro;
    private javax.swing.JMenuItem menuItemParada;
    private javax.swing.JMenuItem menuItemProfundidad;
    private javax.swing.JMenu menuPreferencias;
    private javax.swing.JMenu menuTipoBusqueda;
    private javax.swing.JLabel nroParadas;
    private javax.swing.JLabel redTransporte;
    private javax.swing.JLabel redTransporteSeleccionado;
    private javax.swing.JLabel tipoBusqueda;
    // End of variables declaration//GEN-END:variables
}
