/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.pkg1;

import Objetos.Funcion;
import Objetos.Grafos;
import Objetos.Estacion;
import primitivas.Lista;
import javax.swing.JOptionPane;



/**

 * Esta clase es la interfaz
  
 * @author: Ricardo Paez - Luciano Minardo - Gabriele Colarusso

 * @version: 16/10/2024

 */

public class InterfazFinal extends javax.swing.JFrame {

    private int t = 1; // Valor inicial de t
    private Grafos grafo;
    private Lista<Estacion> estaciones;

    public InterfazFinal() {
        initComponents();
        grafo = new Grafos();
        estaciones = new Lista<>();
    }

    private Estacion buscarEstacionPorNombre(String nombre) {
        nombre = nombre.trim().toLowerCase();
        System.out.println("Buscando estación con nombre: '" + nombre + "'");
        for (int i = 0; i < estaciones.len(); i++) {
            Estacion estacion = estaciones.get(i);
            String nombreEstacion = estacion.getNombre().trim().toLowerCase();
            System.out.println("Comparando con: '" + nombreEstacion + "'");
            if (nombreEstacion.equals(nombre)) {
                System.out.println("¡Estación encontrada!");
                return estacion;
            }
        }
        System.out.println("Estación no encontrada.");
        return null;
    }

    private Lista<Integer> calcularCobertura(Estacion estacionSucursal, int t, String tipoBusqueda) {
        int indiceSucursal = estaciones.indexOf(estacionSucursal);
        boolean[] visitados = new boolean[estaciones.len()];
        Lista<Integer> cobertura = new Lista<>();

        if (tipoBusqueda.equals("BFS")) {
            bfs(indiceSucursal, t, visitados, cobertura);
        } else {
            dfs(indiceSucursal, t, 0, visitados, cobertura);
        }

        return cobertura;
    }

    
    private void bfs(int inicio, int limiteT, boolean[] visitados, Lista<Integer> cobertura) {
        Lista<Integer> cola = new Lista<>();
        int[] niveles = new int[estaciones.len()];

        cola.append(inicio);
        visitados[inicio] = true;
        niveles[inicio] = 0;
        cobertura.append(inicio);

        while (cola.len() > 0) {
            int actual = cola.get(0);
            cola.pop(0);

            if (niveles[actual] >= limiteT) continue;

            Lista<Integer> adyacentes = grafo.getAdyacentes(actual);
            for (int i = 0; i < adyacentes.len(); i++) {
                int vecino = adyacentes.get(i);
                if (!visitados[vecino]) {
                    cola.append(vecino);
                    visitados[vecino] = true;
                    niveles[vecino] = niveles[actual] + 1;
                    cobertura.append(vecino);
                }
            }
        }
    }

    private void dfs(int actual, int limiteT, int nivelActual, boolean[] visitados, Lista<Integer> cobertura) {
        if (nivelActual > limiteT) return;
        visitados[actual] = true;
        cobertura.append(actual);

        Lista<Integer> adyacentes = grafo.getAdyacentes(actual);
        for (int i = 0; i < adyacentes.len(); i++) {
            int vecino = adyacentes.get(i);
            if (!visitados[vecino]) {
                dfs(vecino, limiteT, nivelActual + 1, visitados, cobertura);
            }
        }
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        botonCargarJson = new javax.swing.JButton();
        botonEstablecerT = new javax.swing.JButton();
        obtenerT = new javax.swing.JTextField();
        dfs = new javax.swing.JButton();
        bfs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonVerificarSurcusal = new javax.swing.JButton();
        verificarsurcusal = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCargarJson.setText("Cargar JSON");
        botonCargarJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarJsonActionPerformed(evt);
            }
        });
        getContentPane().add(botonCargarJson, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 27, 150, 70));

        botonEstablecerT.setText("Establecer T");
        botonEstablecerT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstablecerTActionPerformed(evt);
            }
        });
        getContentPane().add(botonEstablecerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 150, 70));
        getContentPane().add(obtenerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 130, -1));

        dfs.setText("DFS");
        dfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfsActionPerformed(evt);
            }
        });
        getContentPane().add(dfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 100, 50));

        bfs.setText("BFS");
        bfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsActionPerformed(evt);
            }
        });
        getContentPane().add(bfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 100, 50));

        jLabel1.setText("Tipo de Busqueda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 130, 50));

        botonVerificarSurcusal.setText("Ver Surcusal");
        botonVerificarSurcusal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerificarSurcusalActionPerformed(evt);
            }
        });
        getContentPane().add(botonVerificarSurcusal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 180, 50));
        getContentPane().add(verificarsurcusal, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 260, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsActionPerformed
         String nombreSucursal = verificarsurcusal.getText();
    if (nombreSucursal != null && !nombreSucursal.trim().isEmpty()) {
        Estacion estacionSucursal = buscarEstacionPorNombre(nombreSucursal.trim());
        if (estacionSucursal != null) {
            Lista<Integer> cobertura = calcularCobertura(estacionSucursal, t, "DFS");
            grafo.resaltarEstaciones(cobertura, estaciones);
        } else {
            JOptionPane.showMessageDialog(this, "Estación no encontrada. Por favor, verifique el nombre.");
        }
    }
    }//GEN-LAST:event_dfsActionPerformed

    private void bfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsActionPerformed
        String nombreSucursal =verificarsurcusal.getText();
    if (nombreSucursal != null && !nombreSucursal.trim().isEmpty()) {
        Estacion estacionSucursal = buscarEstacionPorNombre(nombreSucursal.trim());
        if (estacionSucursal != null) {
            Lista<Integer> cobertura = calcularCobertura(estacionSucursal, t, "BFS");
            grafo.resaltarEstaciones(cobertura, estaciones);
        } else {
            JOptionPane.showMessageDialog(this, "Estación no encontrada. Por favor, verifique el nombre.");
        }
    }
    }//GEN-LAST:event_bfsActionPerformed

    private void botonEstablecerTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstablecerTActionPerformed
        String input = obtenerT.getText();
        try {
            int nuevoT = Integer.parseInt(input);
            if (nuevoT > 0) {
                t = nuevoT;
                JOptionPane.showMessageDialog(this, "El valor de t se ha establecido en " + t);
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un valor de t mayor que cero.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Entrada inválida. Por favor, ingrese un número entero.");
        }
    }//GEN-LAST:event_botonEstablecerTActionPerformed

    private void botonCargarJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarJsonActionPerformed
        grafo = new Grafos();
        estaciones = new Lista<>();
        Funcion.ReadJsonMetro(grafo, estaciones);
        grafo.mostrarGrafo(estaciones);

        System.out.println("Estaciones cargadas:");
        for (int i = 0; i < estaciones.len(); i++) {
            System.out.println("- '" + estaciones.get(i).getNombre() + "'");
        }
    }//GEN-LAST:event_botonCargarJsonActionPerformed

    private void botonVerificarSurcusalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerificarSurcusalActionPerformed
       String nombreSucursal = verificarsurcusal.getText();
        if (nombreSucursal != null && !nombreSucursal.trim().isEmpty()) {
            Estacion estacionSucursal = buscarEstacionPorNombre(nombreSucursal.trim());
            if (estacionSucursal != null) {
                JOptionPane.showMessageDialog(this, "Estación encontrada.");
            } else {
                JOptionPane.showMessageDialog(this, "Estación no encontrada. Por favor, verifique el nombre.");
            }
        }
    }//GEN-LAST:event_botonVerificarSurcusalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazFinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bfs;
    private javax.swing.JButton botonCargarJson;
    private javax.swing.JButton botonEstablecerT;
    private javax.swing.JButton botonVerificarSurcusal;
    private javax.swing.JButton dfs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField obtenerT;
    private javax.swing.JTextField verificarsurcusal;
    // End of variables declaration//GEN-END:variables
}
