package InterfazGUI;

import Objetos.Estacion;
import Objetos.Funcion;
import Objetos.Grafos;
import Objetos.InterfazFunciones;
import Objetos.Sucursal;
import javax.swing.JOptionPane;
import primitivas.Lista;


/**
 * Esta clase es la interfaz
 * 
 * @author: Ricardo Paez - Luciano Minardo - Gabriele Colarusso
 * @version: 16/10/2024
 */
public class InterfazFinal extends javax.swing.JFrame {
    private Grafos grafo;
    private Lista<Estacion> estaciones;
    private Lista<Sucursal> sucursales;
    private InterfazFunciones interfazFunciones;
    private int t = 0; // Valor inicial de t
    private String tipoBusqueda = "";

    public InterfazFinal() {
        initComponents();
        grafo = new Grafos();
        estaciones = new Lista<>();
        sucursales = new Lista<>();
        interfazFunciones = new InterfazFunciones(grafo, estaciones, sucursales);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        botonCargarJson = new javax.swing.JButton();
        botonEstablecerT = new javax.swing.JButton();
        obtenerT = new javax.swing.JTextField();
        dfs = new javax.swing.JButton();
        bfs = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonEliminarSucursal = new javax.swing.JButton();
        agregarSurcusal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BotonVerificarCobertura = new javax.swing.JButton();
        botonAgregarSurcusal1 = new javax.swing.JButton();
        sugerirSurcusal = new javax.swing.JButton();
        agregarLineaNueva = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonCargarJson.setBackground(new java.awt.Color(204, 255, 255));
        botonCargarJson.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        botonCargarJson.setText("Cargar JSON");
        botonCargarJson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarJsonActionPerformed(evt);
            }
        });
        getContentPane().add(botonCargarJson, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 200, 60));

        botonEstablecerT.setBackground(new java.awt.Color(204, 255, 255));
        botonEstablecerT.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        botonEstablecerT.setText("Establecer T");
        botonEstablecerT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEstablecerTActionPerformed(evt);
            }
        });
        getContentPane().add(botonEstablecerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 170, 50));
        getContentPane().add(obtenerT, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 170, -1));

        dfs.setBackground(new java.awt.Color(204, 255, 255));
        dfs.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        dfs.setText("DFS");
        dfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfsActionPerformed(evt);
            }
        });
        getContentPane().add(dfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 100, 50));

        bfs.setBackground(new java.awt.Color(204, 255, 255));
        bfs.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        bfs.setText("BFS");
        bfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsActionPerformed(evt);
            }
        });
        getContentPane().add(bfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 100, 50));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione el algoritmo deseado para colocar ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 310, 20));

        botonEliminarSucursal.setBackground(new java.awt.Color(204, 255, 255));
        botonEliminarSucursal.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        botonEliminarSucursal.setText("Eliminar Sucursal");
        botonEliminarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarSucursalActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 210, 50));
        getContentPane().add(agregarSurcusal, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 350, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Introduzca el numero de T con el cual ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 250, 20));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel3.setText("desea implementar las sucursales.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 360, 220, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel4.setText("Escriba el nombre de la estacion para agregar o eliminar sucursal.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel5.setText("y ver la cobertura de la sucursal.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, -1));

        BotonVerificarCobertura.setBackground(new java.awt.Color(204, 255, 255));
        BotonVerificarCobertura.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        BotonVerificarCobertura.setText("Verificar Cobertura Completa");
        BotonVerificarCobertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonVerificarCoberturaActionPerformed(evt);
            }
        });
        getContentPane().add(BotonVerificarCobertura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 260, 50));

        botonAgregarSurcusal1.setBackground(new java.awt.Color(204, 255, 255));
        botonAgregarSurcusal1.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        botonAgregarSurcusal1.setText("Agregar sucursal");
        botonAgregarSurcusal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAgregarSurcusal1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonAgregarSurcusal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 290, 50));

        sugerirSurcusal.setBackground(new java.awt.Color(204, 255, 255));
        sugerirSurcusal.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        sugerirSurcusal.setText("Sugerir Sucursal");
        sugerirSurcusal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sugerirSurcusalActionPerformed(evt);
            }
        });
        getContentPane().add(sugerirSurcusal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 180, 50));

        agregarLineaNueva.setBackground(new java.awt.Color(204, 255, 255));
        agregarLineaNueva.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        agregarLineaNueva.setText("Agregar Linea Nueva");
        agregarLineaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarLineaNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(agregarLineaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 200, 60));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 260, 30));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 330, -1));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel10.setText("Antes de sugerir sucursal asegurese de haber");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 20));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel11.setText("establecido T y su algoritmo de busqueda.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsActionPerformed
        tipoBusqueda = "DFS";
        JOptionPane.showMessageDialog(this, "El tipo de búsqueda se ha establecido en DFS.");
    }//GEN-LAST:event_dfsActionPerformed

    private void bfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsActionPerformed
        tipoBusqueda = "BFS";
        JOptionPane.showMessageDialog(this, "El tipo de búsqueda se ha establecido en BFS.");
    }//GEN-LAST:event_bfsActionPerformed

    private void botonEstablecerTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEstablecerTActionPerformed
        String input = obtenerT.getText();
        try {
            int nuevoT = Integer.parseInt(input);
            if (nuevoT > 0) {
                t = nuevoT;
                JOptionPane.showMessageDialog(this, "El valor de t se ha establecido en " + t);
            } else {
                JOptionPane.showMessageDialog(this, "Ingrese un valor de t mayor que cero.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Entrada inválida. Por favor, ingrese un número entero.");
        }
    }//GEN-LAST:event_botonEstablecerTActionPerformed

    private void botonCargarJsonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarJsonActionPerformed
        interfazFunciones.inicializarGrafoYEstaciones();
    }//GEN-LAST:event_botonCargarJsonActionPerformed

    private void botonEliminarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarSucursalActionPerformed
       String nombreSucursal = agregarSurcusal.getText().trim();
        interfazFunciones.eliminarSucursal(nombreSucursal);
    }//GEN-LAST:event_botonEliminarSucursalActionPerformed

    private void BotonVerificarCoberturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonVerificarCoberturaActionPerformed
        if (interfazFunciones.todasEstacionesCubiertas()) {
            JOptionPane.showMessageDialog(this, "Todas las estaciones están cubiertas por una sucursal.");
        } else {
            JOptionPane.showMessageDialog(this, "No todas las estaciones están cubiertas.");
        } 
    }//GEN-LAST:event_BotonVerificarCoberturaActionPerformed

    private void botonAgregarSurcusal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAgregarSurcusal1ActionPerformed
    String nombreEstacion = agregarSurcusal.getText().trim();
        interfazFunciones.agregarSucursal(nombreEstacion, t, tipoBusqueda);
    }//GEN-LAST:event_botonAgregarSurcusal1ActionPerformed

    private void sugerirSurcusalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sugerirSurcusalActionPerformed
        if (interfazFunciones.todasEstacionesCubiertas()) {
        JOptionPane.showMessageDialog(this, 
                "Todas las estaciones ya están cubiertas por al menos una sucursal.", 
                "Cobertura Completa", 
                JOptionPane.INFORMATION_MESSAGE);
    } else {
        interfazFunciones.sugerirSucursal(t, tipoBusqueda);
    }
    }//GEN-LAST:event_sugerirSurcusalActionPerformed

    private void agregarLineaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarLineaNuevaActionPerformed
    interfazFunciones.agregarNuevaLinea();
    }//GEN-LAST:event_agregarLineaNuevaActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonVerificarCobertura;
    private javax.swing.JButton agregarLineaNueva;
    private javax.swing.JTextField agregarSurcusal;
    private javax.swing.JButton bfs;
    private javax.swing.JButton botonAgregarSurcusal1;
    private javax.swing.JButton botonCargarJson;
    private javax.swing.JButton botonEliminarSucursal;
    private javax.swing.JButton botonEstablecerT;
    private javax.swing.JButton dfs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField obtenerT;
    private javax.swing.JButton sugerirSurcusal;
    // End of variables declaration//GEN-END:variables
}
